# Generated by Django 5.2.17 on 2026-08-20 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_id", models.CharField(max_length=120)),
                ("calendar", models.CharField(max_length=120)),
                ("timezone", models.CharField(max_length=80)),
                ("rule", models.JSONField(default=dict)),
                ("exceptions", models.JSONField(default=dict)),
                ("priority", models.IntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows",
                        to="maintenance_service.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Override",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_start", models.DateTimeField()),
                ("action", models.CharField(max_length=20)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="maintenance_service.maintenancewindow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="maintenance_service.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="windows",
                to="maintenance_service.resource",
            ),
        ),
        migrations.CreateModel(
            name="CalendarRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="maintenance_service.organization",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="maintenance_service.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("priority", models.IntegerField()),
                ("source", models.CharField(max_length=120)),
                ("revision", models.PositiveIntegerField()),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="maintenance_service.maintenancewindow",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("window", "start"), name="occurrence_unique_start"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                fields=("organization", "key"), name="resource_org_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancewindow",
            constraint=models.UniqueConstraint(
                fields=("organization", "resource", "window_id"), name="window_scope_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "resource"), name="revision_scope"
            ),
        ),
    ]
